### ISSUE TITLE
-M switch to full wire speed after 30min

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#210]
as per user group message...

Cory Simonson cory.simonson@viavisolutions.com via lists.sourceforge.net 
1:43 PM (28 minutes ago)

to tcpreplay-users 
Hello,

I'm experiencing an issue where after about 30 minutes of looping the speed at which traffic is generated changes from what was specified with the -M option to full line rate.

I'm running tcpreplay with netmap on FreeBSD 10.2-RELEASE amd64. This seems to occur regardless of which rate or capture file I use. I'm using a dual-port Intel 10 GbE PCI-E adapter.

Here is an example of how I run tcpreplay when I experience this:

tcpreplay --netmap -i ix0 -K -l 0 -M 6430 ./replayfiles/GSinput1.pcap

Here is the tcpreplay -V output:

tcpreplay version: 4.1.0 (build git:v4.1.0)
Copyright 2013-2014 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta Inc.
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Compiled against libdnet: 1.12
Compiled against libpcap: 1.4.0
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: enabled
Default injection method: bpf send()
Not compiled with Quick TX
Optional injection method: netmap

dmesg output for the 10Gb Intel card:

ix0: <Intel(R) PRO/10GbE PCI-Express Network Driver, Version - 2.8.3> port 0xe880-0xe89f mem 0xf9e80000-0xf9efffff,0xf9e7c000-0xf9e7ffff irq 24 at device 0.0 on pci14
ix0: Using MSIX interrupts with 9 vectors
ix0: Ethernet address: 90:e2:ba:55:10:fc
ix0: PCI Express Bus: Speed 5.0GT/s Width x8
ix0: netmap queues/slots: TX 8/2048, RX 8/2048
ix1: <Intel(R) PRO/10GbE PCI-Express Network Driver, Version - 2.8.3> port 0xec00-0xec1f mem 0xf9f80000-0xf9ffffff,0xf9f7c000-0xf9f7ffff irq 34 at device 0.1 on pci14
ix1: Using MSIX interrupts with 9 vectors
ix1: Ethernet address: 90:e2:ba:55:10:fd
ix1: PCI Express Bus: Speed 5.0GT/s Width x8
ix1: netmap queues/slots: TX 8/2048, RX 8/2048

**Comment by fklassen** [comment]
fixed in PR #221

**Comment by c-f-s-s** [comment]
I'm still experiencing this issue (I'm Cory, the person who reported the issue originally to the mailing list). Last time I made a concerted effort to reproduce, it took about 4 hours. For others, it seemed to occur quicker but, I haven't confirmed if it can occur as quickly as 30 minutes.

Updated information:

FreeBSD 10.3-RELEASE amd64

tcpreplay version: 4.1.1 (build git:v4.1.1)
Copyright 2013-2014 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Compiled against libdnet: 1.12
Compiled against libpcap: 1.4.0
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: enabled
Default injection method: bpf send()
Not compiled with Quick TX
Optional injection method: netmap

**Comment by fklassen** [comment]
I'll reopen the issue and will attempt to reproduce in 4.2 release. I'll probably get around to it in the fall.

**Comment by fklassen** [comment]
There has been some rework to timing logic, mainly in #268. Also #269. This issue is hard to reproduce, so closing for now. Can be reopened if it fails in newer releases.

**Comment by c-f-s-s** [comment]
Unfortunately, I can still reproduce this with v4.2.0-beta1.

**Comment by fklassen** [comment]
Reopening. Thanks for testing.

**Comment by fklassen** [comment]
@c-f-s-s I have tried again to reproduce this on both Linux and FreeBSD. I don't have access to 10GigE for FreeBSD, but I did run for over 10 hours on a GigE network. Cannot reproduce.

I looked at the code, and the only thing I found is that the issue could happen if this is a 32-bit machine. Can you send me the output of `uname -m`, and the `config.h` file?

Fred.

**Comment by c-f-s-s** [comment]
I tried reproducing on my systems igb 1G motherboard port and couldn't there either. I can reproduce it on our 40G card, though.

I had to change the file extension to txt because github didn't like .h...

uname -m output:
amd64

[config.txt](https://github.com/appneta/tcpreplay/files/841280/config.txt)

**Comment by fklassen** [comment]
Yes, it is amd64. I guess I have to get some of my 10GigE hardware booted up on FreeBSD. I wonder if netmap has anything to do with it.

If you ever try a test again with the latest beta, I am trying to get a screen shot of before/after the failure when using the  `--stats=X` command. Note that `--stats=0` is now supported and will report every loop, which is handy when using large PCAP files.

**Comment by fklassen** [comment]
Oh yes, definitely have confirmed that tcpreplay has detected your system as 64-bit.

**Comment by c-f-s-s** [comment]
Testing with beta1 and the --stats flag set to 5 seconds.

I've attached a txt file with the piped output. Interestingly, at the point at which my capture device indicates traffic is coming in at line-rate (3,690 seconds in) the --stats output only indicates a small incremental increase of about 1 Mb per second. As opposed to the reality, which is that it's a straight-shot from 5 Gbps to 10.

[output.txt](https://github.com/appneta/tcpreplay/files/841912/output.txt)

**Comment by fklassen** [comment]
Wow, I was expecting a sudden jump. I've never seen that before. It sounds like an integer math issue. I'll look into it.

**Comment by fklassen** [comment]
@c-f-s-s thanks for hanging in there. I am quite sure I have this fixed, and I also improved accuracy of some of the stats calculation. I hard coded the exact state that your machine was in just before it failed, and I could reproduce the issue within seconds, every time.

The issue is fixed in the second commit.

I will create 4.2-beta2 release soon so you can test.

**Comment by c-f-s-s** [comment]
I can no longer reproduce in the second beta! Thanks very much for looking into this!

I noticed it's printing out every loop now though (I don't have the --stats flag on) like this:

Loop 1615 (1 unique)...
Loop 1616 (1 unique)...
Loop 1617 (1 unique)...
Loop 1618 (1 unique)...

don't think the last beta did this. Wanted to point it out in case it was test output you accidentally left in or something like that.

**Comment by fklassen** [comment]
@c-f-s-s glad that worked for you.

I don't see that issue. Can you send me the command-line parameters you used to recreate it?
