### ISSUE TITLE
Rewrite zero IPv4 total length field to match the actual packet length

### ISSUE THREAD

**Issue by diper** [appneta/tcpreplay#406]
It is possible?

**Comment by fklassen** [comment]
It's possible. Is there a need for it? How would it be used?

**Comment by diper** [comment]
This is needed for fixing pcap files captured with TCP segmentation offloading. Like done in #247

**Comment by fklassen** [comment]
Sounds good. Will schedule work for a future release. Right now we are in a code freeze. Will probably start enhancements again in the Fall.

**Comment by diper** [comment]
Feature seem to be broken...
Before
![image](https://user-images.githubusercontent.com/8170108/36475035-85d2ea3e-170a-11e8-8d05-802def1ff44c.png)
After rewrite
![image](https://user-images.githubusercontent.com/8170108/36475056-97a1fd68-170a-11e8-9219-be0818665283.png)

**Comment by fklassen** [comment]
fixed latest bug in PR #501

**Comment by 1wilkens** [comment]
I think the feature is still broken, as it incorrectly set the IP length to the total length which is not correct as the Link Layer header length needs to be deducted (14 byte for Ethernet).

Before rewriting:
![Before rewriting](https://user-images.githubusercontent.com/2774469/97718396-303bbc00-1ac6-11eb-816a-8f7e264f6c54.png)
After rewriting:
![After Rewriting](https://user-images.githubusercontent.com/2774469/97718424-36ca3380-1ac6-11eb-8ee6-4dad57544937.png)

I could whip up a PR however, due to the modularity of `tcprewrite` regarding Layer 2 types, I am not sure where to get the correct length from.
